apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-web-app
  template:
    metadata:
      labels:
        app: my-web-app
    spec:
      containers:
      - name: my-container
        image: nginx:latest  # Using nginx for simplicity; replace with your app's image
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: my-web-service
spec:
  selector:
    app: my-web-app
  ports:
  - protocol: TCP
    port: 80  # Port exposed by the service
    targetPort: 80 # Port the container is listening on
  type: LoadBalancer # Or ClusterIP if you don't need external access
